import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");
const OUT = join(ROOT, "docs", "gaps");
const PY = join(ROOT, "backend", ".venv", "bin", "python");
const DUMPER = join(ROOT, "backend", "scripts", "spec_fields.py");
const check = process.argv.includes("--check");

// Exit codes follow scripts/schematron-expected.mjs: 0 in sync, 1 stale, 2 cannot run.
function cannotRun(message) {
  console.error(`gap-report: ${message}`);
  process.exit(2);
}

function specFields() {
  if (!existsSync(PY)) cannotRun(`no backend venv at ${PY} — run: make setup`);
  if (!existsSync(DUMPER)) cannotRun(`missing ${DUMPER}`);
  try {
    return JSON.parse(
      execFileSync(PY, [DUMPER], { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 }),
    );
  } catch (error) {
    cannotRun(`the spec dumper failed: ${error.stderr?.trim() || error.message}`);
  }
}

// The report is folded in TypeScript because that is where the mapping tables, the loss tables and
// the BT catalogue live. Vite's own programmatic API loads that module under Node — which is all
// vite-node does — so no extra dependency is needed to run it.
async function load() {
  const server = await createServer({
    root: join(ROOT, "frontend"),
    server: { middlewareMode: true },
    appType: "custom",
    logLevel: "warn",
  });
  try {
    return {
      module: await server.ssrLoadModule("/src/gap-report.ts"),
      close: () => server.close(),
    };
  } catch (error) {
    await server.close();
    cannotRun(`could not load src/gap-report.ts: ${error.message}`);
  }
}

function readme(rows, summary, inputs, spec) {
  const tally = (counts) =>
    Object.entries(counts)
      .sort((a, b) => b[1] - a[1])
      .map(([key, value]) => `| ${key} | ${value} |`)
      .join("\n");
  return `# Field gaps

<!-- Generated by frontend/scripts/gap-report.mjs — do not hand-edit. Run: make gap-report -->

Every invoice field that has no home in one of the three structures the Mapper shows: the canonical
model, the fiskaly \`TRANSACTION::INVOICE\` operation, and the predicted XML for the syntax that
country files. Folded from the sources listed below; this file authors no compliance prose of its
own, and every \`reason\` is quoted verbatim from a declared table.

Scope is **each country's mandated syntax only** — IT → FatturaPA, BE → Peppol UBL, DE → XRechnung
and CII. Gaps in a syntax a country never files are computable but are not reported.

Spec: \`${spec.source}\` (\`${spec.source_sha256.slice(0, 12)}\`), \`X-Api-Version\` ${spec.api_version}.

## Counts

**${rows.length} rows across ${summary.causes} distinct causes.** One ticket per cause, with the
field list as its body — filing one ticket per row would be ${rows.length} tickets nobody triages.

| by format | rows |
|---|---|
${tally(summary.byFormat)}

| missing from | rows |
|---|---|
${tally(summary.byMissingFrom)}

| severity | rows |
|---|---|
${tally(summary.bySeverity)}

| evidence | rows |
|---|---|
${tally(summary.byEvidence)}

## How severity is derived

Nothing here is hand-curated; each row's \`source\` names the rule that set it, so a reviewer can
dispute the rule rather than the row.

| rule | meaning |
|---|---|
| R1 blocking | a term the standard makes mandatory that the mandated syntax renders no element for — nothing downstream can supply it |
| R2 should-fix | the syntax renders it but the operation cannot carry it, so authored data never reaches fiskaly; or a required spec pointer with no model field |
| R3 note | optional, or not applicable for the country's profile |
| R4 platform | the capture shows fiskaly fills this from the Taxpayer or derives it, so its absence from the payload is by design |

A mandatory business term missing from the *operation* is deliberately not blocking: fiskaly derives
BT-3 and takes the seller identity from the commissioned Taxpayer.

## What the evidence column means

\`captured\` cites the one transmission recorded in \`docs/reference/fatturapa/\`. \`unobserved\`
means no capture exists for that syntax — which is **not** the same as "not rendered". \`none\` means
the capture is silent on that pointer; the same document is explicit that it cannot speak for fields
its payload never sent.

## Excluded

${inputs.derivedPaths.length} entries in \`UAPI_DERIVED_PATHS\` are excluded: they are
bracket-notation paths with no per-entry reason, and repeating one module comment ${inputs.derivedPaths.length}
times would present a single claim as ${inputs.derivedPaths.length} independent ones.

${inputs.derivedPaths.map((path) => `- \`${path}\``).join("\n")}

## Verifying these claims

\`make gap-check\` proves the mechanical half: every pointer exists in the contract, every business
term is in the catalogue, every reason is quoted verbatim, and every proposed JSON target still
validates when spliced into that country's invoice.

What no schema can settle — whether a gap is *real*, whether \`belongsAt\` is the semantically right
home, and whether \`blocking\` is the right call — is settled by the \`/gap-audit\` workflow, which
runs a reviewer over each cause against the standards and then adversarially tries to refute it.
Save its output as \`docs/gaps/verdicts.json\`; \`backend/tests/test_gap_verdicts.py\` then keeps it
honest, failing when a verdict outlives its row or the reason it judged is re-worded.
${
  (summary.bySeverity.blocking ?? 0) > 0
    ? `
Note that the blocking rows apply EN 16931 cardinality to FatturaPA, which is **not** a CIUS of
EN 16931. Whether that is a gap or a category error is exactly what the research run should decide.
`
    : ""
}
## Jira mapping

\`gap-report.csv\` is importable as-is. \`summary\` is the issue Summary, \`id\` the External issue ID
so a re-import updates rather than duplicates, \`severity\` maps to Priority (blocking→High,
should-fix→Medium, note→Low), \`format\` to Component, and \`format\`/\`missingFrom\` to labels.

## Sources

${inputs.sources.map((file) => `- \`${file}\``).join("\n")}
`;
}

function unmatchedDoc(unmatched, suppressed) {
  const row = (entry) =>
    `| ${entry.format} | \`${entry.field}\` | ${entry.bt ?? "—"} | ${entry.term ?? "—"} | ${entry.why} |`;
  return `# Fields the prediction could not match

<!-- Generated by frontend/scripts/gap-report.mjs — do not hand-edit. Run: make gap-report -->

The predicted XML shows what fiskaly will generate, not what our writers can. A field the operation
cannot carry is dropped from the prediction **only** when nothing else supplies it; fiskaly derives
some fields itself — BT-3, the seller identity from the commissioned Taxpayer, the recomputed VAT
summary, the defaulted payment method — and those still appear in the transmitted document.

## Dropped from the prediction (${suppressed.length})

Nothing delivers these, so the transmitted document will not contain them.

| format | field | BT | term | why |
|---|---|---|---|---|
${suppressed.map(row).join("\n")}

## Not matched (${unmatched.length})

The syntax renders these and we cannot yet say whether the operation delivers them or fiskaly fills
them in. **They are still shown** — absence of evidence is not evidence of absence — and they are
the list to settle, by review or by a captured transmission.

| format | field | BT | term | why |
|---|---|---|---|---|
${unmatched.map(row).join("\n")}
`;
}

const { module, close } = await load();
const dumped = specFields();
const snapshots = module.MANDATED.map(({ country, format }) => ({
  country,
  format,
  spec: dumped[country],
}));

const rows = module.gapRows(snapshots);
const unmatched = module.unmatchedRows();
const suppressed = module.suppressedRows();
const summary = module.gapSummary(rows);
const inputs = { ...module.gapInputs(), sources: [...module.GAP_INPUTS] };
const spec = dumped.IT;

const files = {
  "gap-report.json": `${JSON.stringify(rows, null, 2)}\n`,
  "gap-report.csv": module.toCsv(rows),
  "README.md": readme(rows, summary, inputs, spec),
  "unmatched.md": unmatchedDoc(unmatched, suppressed),
  "inputs/model-fields.json": `${JSON.stringify(inputs.modelFields, null, 2)}\n`,
  "inputs/pointer-fields.json": `${JSON.stringify(inputs.pointerFields, null, 2)}\n`,
  "inputs/declared-reasons.json": `${JSON.stringify(inputs.declaredReasons, null, 2)}\n`,
  "inputs/derived-paths.json": `${JSON.stringify(inputs.derivedPaths, null, 2)}\n`,
};
for (const [format, paths] of Object.entries(inputs.mappingPaths)) {
  files[`inputs/mapping-paths.${format}.json`] = `${JSON.stringify(paths, null, 2)}\n`;
}

await close();

const contradictions = module.presetContradictions(rows);
if (contradictions.length > 0) {
  console.error(
    `gap-report: ${contradictions.length} row(s) disagree with the live per-field verdict:\n` +
      contradictions.map((entry) => `  ${entry.id} (${entry.preset}): ${entry.note}`).join("\n"),
  );
  process.exit(2);
}

if (check) {
  const stale = Object.entries(files).filter(([name, body]) => {
    const path = join(OUT, name);
    return !existsSync(path) || readFileSync(path, "utf8") !== body;
  });
  if (stale.length > 0) {
    console.error(
      `gap-report: ${stale.length} file(s) out of date — run: make gap-report\n` +
        stale.map(([name]) => `  docs/gaps/${name}`).join("\n"),
    );
    process.exit(1);
  }
  console.log(`gap-report ok (${rows.length} rows, ${summary.causes} causes)`);
  process.exit(0);
}

mkdirSync(join(OUT, "inputs"), { recursive: true });
for (const [name, body] of Object.entries(files)) writeFileSync(join(OUT, name), body);
console.log(
  `gap-report: ${rows.length} rows, ${summary.causes} causes, ` +
    `${suppressed.length} suppressed, ${unmatched.length} unmatched -> docs/gaps/ ` +
    `(${summary.bySeverity.blocking ?? 0} blocking, ${summary.bySeverity["should-fix"] ?? 0} should-fix)`,
);
