import type { FormatId } from "./model";
import { pointerTemplate } from "./uapi-map";

// What fiskaly's gateway actually does with each field of a `TRANSACTION::INVOICE` operation,
// encoded as data. Evidence: one real request and the FatturaPA XML the gateway generated from
// it, captured 2026-08-25 (docs/reference/fatturapa/ — tested-payload.json, tested-response.xml,
// README.md), cross-checked against the 2026-06-01 spec (spec/fiskaly.uapi.e-invoice-it.yaml).
//
// The evidence covers the FatturaPA/IT path only, so the table is scoped to `formatId
// "fatturapa"` and `fateFor` answers `undefined` for every other format. A pointer without an
// entry means "no evidence", not "mapped": `references.project` and `references.despatch_advice`
// are deliberately absent because the capture proves nothing about them.

export type FieldFate = "mapped" | "not-rendered" | "discarded" | "platform";

export type FateEntry = {
  pointer: string;
  fate: FieldFate;
  element?: string;
  note: string;
};

const BOTH_TRUE =
  "The 2026-06-01 spec still requires it on an INVOICE operation, so it must be sent even " +
  "though it is ignored; both statements are true at once.";

const DETAILS_DISCARDED =
  "Accepted by the schema, then thrown away by the FatturaPA generator — only `concept` " +
  "survives from the details block.";

export const FATTURAPA_FATES: FateEntry[] = [
  // DatiTrasmissione — the envelope around the destination code is platform-generated.
  {
    pointer: "/recipients/{i}/invoicing/destination_code",
    fate: "mapped",
    element: "DatiTrasmissione/CodiceDestinatario",
    note:
      "The SDI destination code is written to CodiceDestinatario; the rest of the transmission " +
      "envelope (IdTrasmittente, ProgressivoInvio, FormatoTrasmissione) is generated by the " +
      "platform and cannot be authored from the request.",
  },

  // CedentePrestatore — the seller is not authored per invoice.
  {
    pointer: "/seller",
    fate: "platform",
    element: "CedentePrestatore",
    note:
      "The seller's identity, address, RegimeFiscale and IscrizioneREA come from the " +
      "commissioned Taxpayer entity, not from this request; only the phone and email in this " +
      "block reach the XML, as the contact point.",
  },
  {
    pointer: "/seller/name",
    fate: "not-rendered",
    note:
      "Accepted by the schema (BT-41 seller contact point) but FatturaPA's Contatti block has " +
      "no name element, so it produced no output in the tested capture.",
  },
  {
    pointer: "/seller/phone",
    fate: "mapped",
    element: "CedentePrestatore/Contatti/Telefono",
    note:
      "The seller phone becomes Contatti/Telefono; the tested capture shows it reformatted " +
      "(+39123456789 came back as 123456789).",
  },
  {
    pointer: "/seller/email",
    fate: "mapped",
    element: "CedentePrestatore/Contatti/Email",
    note: "The seller email becomes Contatti/Email, unchanged in the tested capture.",
  },
  {
    pointer: "/tax_representative",
    fate: "not-rendered",
    note:
      "Accepted by the schema, but no RappresentanteFiscale block appeared in the tested " +
      "capture even though the request named one.",
  },

  // CessionarioCommittente
  {
    pointer: "/recipients/{i}/name",
    fate: "mapped",
    element: "CessionarioCommittente/DatiAnagrafici/Anagrafica/Denominazione",
    note: "The business recipient's name becomes the buyer's Denominazione.",
  },
  {
    pointer: "/recipients/{i}/identification/number",
    fate: "mapped",
    element: "CessionarioCommittente/DatiAnagrafici/IdFiscaleIVA/IdCodice",
    note:
      "A VAT identification becomes the buyer's IdFiscaleIVA, written as the bare national " +
      "number without the IT prefix.",
  },
  {
    pointer: "/recipients/{i}/address",
    fate: "mapped",
    element: "CessionarioCommittente/Sede",
    note:
      "The recipient address becomes the buyer's Sede: street, number, postcode, city, region " +
      "(Provincia) and country all rendered in the tested capture.",
  },
  {
    pointer: "/recipients/{i}/buyer_id",
    fate: "not-rendered",
    note:
      "Accepted by the schema (BT-46 buyer identifier) but produced no element in the tested " +
      "capture.",
  },
  {
    pointer: "/recipients/{i}/company_id",
    fate: "not-rendered",
    note:
      "We send the buyer's legal registration number here (BT-47); the schema accepts it and " +
      "the tested capture shows no element for it. It stays in the payload because this " +
      "evidence covers FatturaPA only — other syntaxes may render it.",
  },
  {
    pointer: "/recipients/{i}/shipping",
    fate: "not-rendered",
    note:
      "Accepted by the schema, but no DatiTrasporto block appeared in the tested capture even " +
      "though the request carried a full shipping address and date.",
  },

  // DatiGenerali — document identity and references.
  {
    pointer: "/document/number",
    fate: "mapped",
    element: "DatiGeneraliDocumento/Numero",
    note: "The document number becomes Numero, unchanged.",
  },
  {
    pointer: "/document/issued_at",
    fate: "mapped",
    element: "DatiGeneraliDocumento/Data",
    note:
      "The issue date becomes Data (BT-2). The 2026-06-01 spec requires only document.number, " +
      "and the tested capture — which omitted issued_at — shows Data platform-defaulted to the " +
      "transmission date; we always send it so the issue date stays author-controlled.",
  },
  {
    pointer: "/document/payment_terms",
    fate: "not-rendered",
    note:
      "The tested payload sent free-text payment terms and no element carried them; FatturaPA " +
      "expresses terms as the coded CondizioniPagamento, which the platform derives itself.",
  },
  {
    pointer: "/document/references/purchase_order",
    fate: "mapped",
    element: "DatiGenerali/DatiOrdineAcquisto",
    note: "The purchase order reference becomes DatiOrdineAcquisto/IdDocumento.",
  },
  {
    pointer: "/document/references/contract",
    fate: "mapped",
    element: "DatiGenerali/DatiContratto",
    note: "The contract reference becomes DatiContratto/IdDocumento.",
  },
  {
    pointer: "/document/references/tender",
    fate: "mapped",
    element: "DatiGenerali/DatiConvenzione",
    note: "The tender reference becomes DatiConvenzione/IdDocumento.",
  },
  {
    pointer: "/document/references/preceding_document",
    fate: "mapped",
    element: "DatiGenerali/DatiFattureCollegate",
    note:
      "The preceding document becomes DatiFattureCollegate, with both IdDocumento and Data " +
      "rendered in the tested capture.",
  },
  {
    pointer: "/document/references/buyer",
    fate: "not-rendered",
    note:
      "Accepted by the schema (BT-10 buyer reference) but produced no element in the tested " +
      "capture.",
  },
  {
    pointer: "/document/references/buyer_routing",
    fate: "not-rendered",
    note:
      "Accepted by the schema (BT-19 buyer accounting reference) but produced no element in " +
      "the tested capture.",
  },

  // DatiBeniServizi — lines are mapped, your VAT summary is not.
  {
    pointer: "/entries/{i}/data/text",
    fate: "mapped",
    element: "DettaglioLinee/Descrizione",
    note: "The entry text (BT-153 item name) becomes the line's Descrizione.",
  },
  {
    pointer: "/entries/{i}/data/unit/quantity",
    fate: "mapped",
    element: "DettaglioLinee/Quantita",
    note:
      "The quantity becomes Quantita, reformatted by the gateway (1 came back as 1.00000000 in " +
      "the tested capture).",
  },
  {
    pointer: "/entries/{i}/data/unit/measure",
    fate: "not-rendered",
    note:
      "Free text in the 2026-06-01 spec (BT-130, PlainString32); the tested capture sent " +
      '"unit" and no UnitaMisura element appeared. We send UN/ECE Rec 20 codes such as C62, ' +
      "which are equally schema-valid; whether a recognised code would render UnitaMisura is " +
      "unproven.",
  },
  {
    pointer: "/entries/{i}/data/unit/price/exclusive",
    fate: "mapped",
    element: "DettaglioLinee/PrezzoUnitario",
    note:
      "The net unit price becomes PrezzoUnitario, reformatted by the gateway (100.00 came back " +
      "as 100.0000 in the tested capture).",
  },
  {
    pointer: "/entries/{i}/data/value/base",
    fate: "mapped",
    element: "DettaglioLinee/PrezzoTotale",
    note: "The entry's base value becomes the line's PrezzoTotale.",
  },
  {
    pointer: "/entries/{i}/data/vat/percentage",
    fate: "mapped",
    element: "DettaglioLinee/AliquotaIVA",
    note: "The VAT percentage becomes the line's AliquotaIVA.",
  },
  {
    pointer: "/entries/{i}/data/product",
    fate: "discarded",
    note:
      "Accepted by the schema, then thrown away by the FatturaPA generator; no product details " +
      "reach the XML.",
  },
  {
    pointer: "/entries/{i}/details/concept",
    fate: "not-rendered",
    note:
      "The one details field the generator keeps — it classifies the entry as GOOD or SERVICE " +
      "— but no FatturaPA element depends on it in the tested capture. We derive it from the " +
      "unit code (HUR means SERVICE), which matched the tested consulting line.",
  },
  {
    pointer: "/entries/{i}/details/description",
    fate: "discarded",
    note:
      "We send the line description here (BT-127 invoice line note) and the FatturaPA " +
      "generator throws it away — only `concept` survives from the details block. It stays in " +
      "the payload because the schema accepts it and this evidence does not cover the UBL and " +
      "CII paths, which may use it.",
  },
  {
    pointer: "/entries/{i}/details/number",
    fate: "discarded",
    note:
      "We send the line id here and the FatturaPA generator throws it away; NumeroLinea is " +
      "assigned from the entry's position instead. It stays in the payload because the schema " +
      "accepts it and this evidence covers FatturaPA only.",
  },
  { pointer: "/entries/{i}/details/purpose", fate: "discarded", note: DETAILS_DISCARDED },
  { pointer: "/entries/{i}/details/regulatory", fate: "discarded", note: DETAILS_DISCARDED },
  { pointer: "/entries/{i}/details/label", fate: "discarded", note: DETAILS_DISCARDED },
  { pointer: "/entries/{i}/details/properties", fate: "discarded", note: DETAILS_DISCARDED },

  // breakdown[] and totals — schema-required, then thrown away.
  {
    pointer: "/breakdown",
    fate: "discarded",
    element: "DatiBeniServizi/DatiRiepilogo",
    note:
      "The VAT breakdown you send is thrown away — DatiRiepilogo is always recomputed " +
      "server-side from the lines. " +
      BOTH_TRUE,
  },
  {
    pointer: "/totals",
    fate: "discarded",
    element: "DatiBeniServizi/DatiRiepilogo",
    note:
      "The totals you send are thrown away and recomputed server-side along with " +
      "DatiRiepilogo. " +
      BOTH_TRUE,
  },

  // DatiPagamento
  {
    pointer: "/payments/{i}/details/amount",
    fate: "mapped",
    element: "DettaglioPagamento/ImportoPagamento",
    note: "The payment amount becomes ImportoPagamento.",
  },
  {
    pointer: "/payments/{i}/details/currency",
    fate: "mapped",
    element: "DatiGeneraliDocumento/Divisa",
    note: "The document currency (Divisa) is taken from the payment details.",
  },
  {
    pointer: "/payments/{i}/details/date",
    fate: "mapped",
    element: "DettaglioPagamento/DataScadenzaPagamento",
    note: "The payment date on an OUTSTANDING payment becomes DataScadenzaPagamento.",
  },
  {
    pointer: "/payments/{i}/details/discount",
    fate: "discarded",
    note:
      "Accepted by the schema, then thrown away by the FatturaPA generator; no payment " +
      "discount reaches the XML.",
  },
  {
    pointer: "/payments/{i}/concept",
    fate: "discarded",
    note:
      "Accepted by the schema (GOOD, SERVICE or INVOICE), then thrown away by the FatturaPA " +
      "generator; the tested capture sent SERVICE and we send INVOICE, and neither reaches the " +
      "XML.",
  },
  {
    pointer: "/payments/{i}/instruction/account",
    fate: "mapped",
    element: "DettaglioPagamento/IBAN",
    note: "The credit-transfer account becomes the IBAN element.",
  },
  {
    pointer: "/payments/{i}/instruction/name",
    fate: "mapped",
    element: "DettaglioPagamento/IstitutoFinanziario",
    note:
      "The instruction's account-holder name is written as IstitutoFinanziario — FatturaPA's " +
      "financial-institution name — exactly as observed in the tested capture.",
  },
  {
    pointer: "/payments/{i}/instruction/payment_service_provider",
    fate: "mapped",
    element: "DettaglioPagamento/BIC",
    note: "The payment service provider becomes the BIC element and must be a real SWIFT/BIC.",
  },
  {
    pointer: "/payments/{i}/instruction/type",
    fate: "platform",
    element: "DettaglioPagamento/ModalitaPagamento",
    note:
      "The request has no field for ModalitaPagamento; the platform derives a default (MP05, " +
      "bank transfer, in the tested capture), so the model's payment.italianMeansCode cannot " +
      "influence the XML.",
  },
  {
    pointer: "/payments/{i}/type",
    fate: "platform",
    element: "DatiPagamento/CondizioniPagamento",
    note:
      "The request has no field for CondizioniPagamento; the platform derives a default (TP02, " +
      "full payment, in the tested capture), so the model's payment.conditions cannot " +
      "influence the XML.",
  },
];

const FATES_BY_FORMAT: Partial<Record<FormatId, ReadonlyMap<string, FateEntry>>> = {
  fatturapa: new Map(FATTURAPA_FATES.map((entry) => [entry.pointer, entry])),
};

// Resolves a concrete pointer (`/entries/0/details/description`, or `/data/...` inside a
// CORRECTION) against the fate table the same way fieldForPointer resolves fields: numeric
// segments become `{i}` via pointerTemplate. A pointer without its own entry inherits the fate
// of its closest listed ancestor — everything under a discarded `/breakdown` is discarded —
// and a pointer with no listed ancestor has no recorded evidence, so the answer is undefined.
export function fateFor(formatId: FormatId, pointer: string): FateEntry | undefined {
  const table = FATES_BY_FORMAT[formatId];
  if (!table) return undefined;
  const parsed = pointerTemplate(pointer);
  if (!parsed) return undefined;
  let template = parsed.template;
  while (template) {
    const entry = table.get(template);
    if (entry) return entry;
    template = template.slice(0, template.lastIndexOf("/"));
  }
  return undefined;
}
